config/routes.rb
Rails.application.routes.draw do
  get 'todos/index'
  get 'checklist/create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  resources :todos, only: :index do
    resources :checklists, only: :create
  end
  resources :checklists, only: :index
  get 'checklists/:id/edit', to: 'checklists#edit', as: 'edit'
  patch 'checklists/:id', to: 'checklists#update', as: 'checklist/update'
  get 'checklists/:id/complete', to: 'checklists#complete', as: 'complete'

  root to: 'todos#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :user
  belongs_to :todo

end

app/models/todo.rb
class Todo < ApplicationRecord
	has_many :checklists
	has_many :users, through: :checklists

	def done?(user)
    checklists.where(user: user).any? ? true : false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :checklists
  has_many :todos, through: :checklists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
	before_action :authenticate_user!

  def index
    @todos = Todo.all
    @checklist = current_user.checklists
    @user = User.all
  end

  def create
    @todo = Todo.find(params[:todo_id])
    @checklist = Checklist.find_by(todo: @todo, user: current_user)
    if @checklist == nil
      @checklist = Checklist.create(todo: @todo, user: current_user)
    end
    if @checklist.save
      redirect_to root_path, notice: 'Has completado esta tarea'
    else
      redirect_to root_path, alert: 'No has podido completar la tarea' 
    end
  end

  def edit
    @checklist = checklist.find(params[:id])
  end

  def update
    @checklist = checklist.find(params[:id])
    @checklist.update(checklists_params)
    redirect_to root_path
  end

  def complete
    @checklist = checklist.find(params[:id])
    @checklist.checklist = true
    @checklist.save
    redirect_to checklists_path
  end

  private

  def checklist_params
    params.require(:done).permit(:done)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todos = Todo.all
    @todo = Todo.find(params[:id])
    @user = User.all
    @check = Checklist.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/checklists/index.html.erb
<div class="container">
  <div class="row">
    <% @checklist.each_slice(3) do |row| %>
      <% row.each do |s| %>
        <div class="col-md-4">
          <%= image_tag s.todo.photo, class: 'img-fluid' %>
          <h4><%= s.todo.name %></h4>
        </div>
      <% end %>
      <div class="w-100"></div>
    <% end %>
  </div>
  <%= link_to 'Volver', root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ToDo", root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "Tareas realizadas #{current_user.checklists.where(done: false).count} / #{@todos.count} ", checklists_path, class:'nav-link' %>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
            <%= current_user.email %>
          <% else %>
            Ingresar
          <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
              <%= link_to "Salir", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
            <% else %>
              <%= link_to "Ingresar", new_user_session_path, class:'dropdown-item' %>
              <%= link_to "Registrar", new_user_registration_path, class:'dropdown-item' %>
            <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<div class="container">
  <div class="row">
    <% @todos.each_slice(3) do |row| %>
      <% row.each do |todos| %>
        <div class="col">
          <div class="card">
            <%= image_tag todos.photo, class: 'img-fluid' %>
            <h4><%= todos.name %></h4>
            <% unless todos.done?(current_user) %>
              <%= link_to 'Terminar', todo_checklists_path(todos), class: 'btn btn-primary', method: :post %>
            <% else %>
              <%= link_to "Tarea Terminada","#", class:'btn btn-secondary' %>
            <% end %>
           <%= link_to "Detalles", todos , class:'btn btn-dark' %>
          </div>
        </div>
      <% end %>
      <div class="w-100"></div>
    <% end %>
  </div>
</div>

app/views/todos/show.html.erb
<div class="container">
  <h3><%="Ususarios que han completado #{@todo.name}" %> </h3>
  <ul>
  <% @todo.users.each do |i| %>
      <li><%= i.email %></li>
  <% end %>
  </ul>
</div>
  <div class="container">
    <h4><%="Primeros 5 Usuarios en completar #{@todo.name}"%></h4>
    <ul><% @todo.users.order('created_at ASC').limit(5).each do |i| %>
      <li class="row">
        <div class="col">
          <p><%= i.email %></p>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="container">
    <%= link_to  "Volver", todos_path, class:'btn btn-secondary' %>  
  </div>